### ISSUE TITLE
Resource Files view not in a Table 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#136]
The UI mock-ups we agreed to had the resource files in a table
made up of 3 rows:

Image | Name | Description

And in the Descriptions view there was to be a
HTML Summary/Details that would list all the other information (Language, Type, Format, Length, etc.)
Alt="Table view of Resource files, with a thumbnail Image of the resource in the first column, the resource name in the 2nd column and description of this resource file as well as a collapsed Details text control in the 3rd column."
![Screen Shot 2020-06-18 at 2 02 59 PM](https://user-images.githubusercontent.com/7736749/85071533-81c55900-b16c-11ea-9430-a564b51fa823.png)

Alt="Table view of Resource files, with a thumbnail Image of the resource in the first column, the resource name in the 2nd column and description of this resource file as well as an expandedDetails text control in the 3rd column showing the File Type, Format, Language, Accessibility accommodation and license information."
![Screen Shot 2020-06-18 at 2 03 14 PM](https://user-images.githubusercontent.com/7736749/85071541-8427b300-b16c-11ea-8158-565564bd240d.png)

After showing the program manager the latest implementation she wants us to go back to the original design we had with the table view shown above.  Why did we change to this linear view without the HTML Summary/Details for the Details of a resource?

**Comment by sinabahram** [comment]
@clapierre  the summary/details can absolutely be reinstated, but as I mentioned a few times before, tables are incredibly difficult on mobile/iPad. Essentially, a table-based view is going to be impossible to make fully responsive, and responsive was one of the primary goals/responsibilities we had. Also, tons of accessibility implications from being zoomed-in to different screen size usage (all of which come back to the same underlying issue with tables). Let's figure out the table/linear issue first, as the html summary/details is just a consequence, and also is independent of the table issue.

**Comment by jkva** [comment]
All right, so what I ended up doing is flexibly flow the content in a resource file. It displays on a single row when it can, and shrinkw'raps within with the restricted container when the viewport shrinks. @clapierre let me know what you think.

**Comment by clapierre** [comment]
I was going to suggest using CSS flexbox. Is that what you used?

**Comment by jkva** [comment]
Already did, just added some more rules 👍

**Comment by jkva** [comment]
@clapierre is this still an outstanding issue at this point?

**Comment by clapierre** [comment]
I need to show the Program manager on Monday the updated layout, and with the new issue with images #141, we may need more tweaking on this.

**Comment by sinabahram** [comment]
How did that go, @clapierre?

**Comment by clapierre** [comment]
Meeting is scheduled for Tomorrow afternoon
Charles

**Comment by clapierre** [comment]
Sorry was closed by mistake.

The meeting went well, both Lisa and Amaya like the responsive Flex Grid design.

However when I showed them some results with additional data that was added yesterday from he DCMP library both were very concerned about the amount of text because of the descriptions of some resources being quite long.

Ideally we would want to see only the first sentence of the description with ... if there is additional sentences in the description, (which one could click on to expand the additional details.)

So it would behave using the HTML summary/details with the summary being "Sentence one of the description..." and the details containing the rest of the description.

**Comment by sinabahram** [comment]
Charles, will you be defining where these break points are on a per-resource level? There’s no way for us to easily/reliably detect “first sentence”. Periods and punctuation and such can all be used in a variety of ways from things like “Ph.D.” giving us false sentence boundaries, etc., so how do you wish to handle this?

 

For the record, I think this is a bad choice for accessibility and for usability and would suggest that we use some margins or other visual mechanisms to tighten things up, but to display all text. This just forces users to hit more keys and do more things so that a sighted user doesn’t have to scroll a bit more, an operation which is far easier for said sighted mouse-user than it ever will be to open/collapse content for keyboard users, magnification users, screen reader users, etc.

 

Please advise so we know how to implement.

**Comment by clapierre** [comment]
Actually why don't we just always show the first 150 characters and have ... wherever it ends up

EG:
Tongue taste areas the tongue is a muscular organ in the mouth of most vertebrates that manipulates food for mastication, and is used in the act of s… 

Now ideally for mobile this would be 50 characters instead, but if we can't easily do that its fine to just stop after 150 characters.

How does that sound @sinabahram?

**Comment by sinabahram** [comment]
Understood on 150 characters as the stop point.

 

Next question:

How do you plan on making the summary button for each thing unique?

 

It can’t be a plus sign, nor can it say “read more”, as neither of those are unique to a resource.

**Comment by clapierre** [comment]
Hi @sinabahram, it wouldn't be a button. its an HTML Summary/Details so the Summary is unique as its the entire 150 characters which then has the open/close carrot beside that summary which opens up the details.

**Comment by sinabahram** [comment]
Yes, it would be a button, because that’s what browsers map that element to. And, this absolutely will not work. We can’t have a button with a 150 character long description.

 

Think of summary/details as a button whose aria-expanded gets done for you. That’s all it is. nothing more.

 

So, this would read as a button whose label is the entire 150 character long description, followed by the word “collapsed”.

**Comment by jkva** [comment]
How about using CSS for this? `text-overflow:ellipsis`? That way it can be responsive, the full text is still available to screen readers, and it can either be expanded to full when the resource link receives focus, or when the mouse hovers over the resource list item.

**Comment by sinabahram** [comment]
Sorry won’t work. Then SR users have a link to deal with even though it does nothing for them, and we can’t not give them that link because sighted keyboard users then won’t be able to actuate said link, since they aren’t an SR user and need to expand it.

**Comment by jkva** [comment]
I mean the default resource link which already exists, unless we are dealing with the detail page and it should also be constricted on the detail page and not just in the search results.

The main thing indeed is the discoverability of whatever makes the layout switch between ellipsis and full.

**Comment by clapierre** [comment]
So couldn't the unique button name to expand the full details be "Resource Name: Full Description" ?

**Comment by sinabahram** [comment]
no, because that would be redundant/verbose in terms of speech, and also not presumably reflective of its visible label.

 

Here’s the user story you should think through.

 

Think about Alex. He’s a voice dictation user from time to time. What exact command will he give his voice control software to expand the third entry’s text?

 

I think the ultimate solution here is that we force folks to open the resource to see more of the description and that we do not allow for any expansion on this page.

**Comment by sinabahram** [comment]
Sorry to bug! I wanted to follow up on this because I see it as the most critical blocker to moving things forward.

**Comment by clapierre** [comment]
Yeah I was just about to suggest that as well then just have the first 150 characters with ... and no option to expand.  
The other option would be to have each of the resources found be numbered so then you could open Details for Resource 10 for example.  then you could also open Resource 10 vs. saying its name, but we already have the linked name which is probably better anyways.

**Comment by sinabahram** [comment]
Agreed on the first option, so @jkva , this is a truncation task now for the template. Thanks @clapierre

**Comment by clapierre** [comment]
@sinabahram can we have this limited to 75 characters when being displayed initially on mobile?  I am not suggesting that if you open this with your desktop and you have 150 characters then start to shrink the screen size that at some point it switches to 75 characters but if it could that would be fine too.  Just that when the page loads if the screen size is mobile size then have 75 characters, otherwise have 150 characters.

**Comment by sinabahram** [comment]
It will actually have to work the other way e.g. flow from 150 to 75 or vice versa, because there needs to be a knowledge of a person’s screen, and so the issue is that the server doesn’t know this unless if it relies on user-agent strings. @jkva is it possible to do any form of this? So, without going into browser-sniffing or anything like that. Can we just with media-queries address 150 down to 75 for typical mobile?

 

I really do hesitate because I’m afraid we’ll open ourselves up to tons of edge cases, but Job should weigh in.

 

Also, I don’t wish to cause flicker e.g. the 150 is sent out, then CSS is used t hide or show part of it.

**Comment by jkva** [comment]
@sinabahram no browser sniffing please. At that point I'd rather use javascript for some progressive enhancement. Get the viewport size and clip the text down based on that.

**Comment by jkva** [comment]
@clapierre I've currently clamped it with CSS so it's responsive on viewports. This is only on search results, so the detail page review still displays the entire description. Let me know what you think.

**Comment by clapierre** [comment]
WOW @jkva your the man, works better than I hoped! 
I say this is done!
