### ISSUE TITLE
File Type Icons: Search Results Page & Resources contained within Collections

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#158]
This applies for either a Search Results Page or viewing the resources of a collection.

Yesterday Both Lisa and Amaya seeing these pages for the first time both agreed that we need to include the File types of the resource files making up the resources shown on this page, so that one knows the options available before clicking into the resource.  Granted they could also do this by additional filtering but not everyone will use the advance filters for this purpose.

For example: "Frog Dissection 2D" we have the following File types of the resource files making up this resource
Text Document, PDF, 2D Tactile Graphic

We would like to see the new Icons with their alt-text descriptions for the file types available with this resource.

IE:
Alt: Text Document, PDF, 2.5 D Tactile Graphic
Available File Types:  ![TXT-72](https://user-images.githubusercontent.com/7736749/85562520-68dffc00-b5e1-11ea-8761-ef4f095192fc.png) ![PDF-72](https://user-images.githubusercontent.com/7736749/85562553-6f6e7380-b5e1-11ea-8dfb-ef38b35473f9.png) ![2_5_d-72](https://user-images.githubusercontent.com/7736749/85562652-8b721500-b5e1-11ea-8c0c-792265651854.png)

This would appear after the Name of the resource, then would come the image and its description, followed by the source.  Alternatively we could include this before the source, if it makes more sense to have it there.

**Comment by jkva** [comment]
Since we already have these types as custom taxonomy terms, I would prefer to re-use these. So here's what I did:

![Screen capture of "Frog dissection" resource, showing file type icons to the right of the resource title](https://user-images.githubusercontent.com/217264/85621049-f7499180-b664-11ea-9050-918c760e4bc2.png)

These images come from my local install's media library and have been associated to the type in question. The alt text is the same as the term name, which in my opinion it should be, rather than a custom alt text for the image that's separately defined.

![Screen capture of "2D Tactile image" term editing form, showing a custom thumbnail field](https://user-images.githubusercontent.com/217264/85621226-37107900-b665-11ea-90c2-4efe5e9d6018.png)

How about this? It allows for flexibility as the list of types grows.

**Comment by clapierre** [comment]
so these would be in Tags but are special versions for file types? just wondering where that page you are showing above?  Because some tags wouldn't have images obviously.

**Comment by jkva** [comment]
They're the existing set of defined types
![image](https://user-images.githubusercontent.com/217264/85621871-3fb57f00-b666-11ea-8661-380c3d82e804.png)

**Comment by clapierre** [comment]
Oh then shouldn't that say "Add new Type?  It says "Tag"
and also "Edit Tag" vs. Type :)

**Comment by clapierre** [comment]
Which is why I was confused :)

**Comment by jkva** [comment]
Good point. Addressing in https://github.com/benetech/Imageshare/issues/161.

Are you otherwise agreeing with this implementation?

**Comment by clapierre** [comment]
Yes that works for me, once we can see it live I will show Lisa and Amaya, but I think that will work.

**Comment by jkva** [comment]
Implemented via 4d3e8bd800ac4ba79eda1e6f21fc2280dc0051c0

**Comment by clapierre** [comment]
@jkva I like the design, but the images does not reflect the underlying data yet it seems.
I wouldn't have expected this ticket closed until that was working.  Or is there another issue to reflect this?
IE: Video resource should just have the Video File type icon in the Search Results and Resource Results page.

**Comment by jkva** [comment]
@clapierre looks like something's off with the database on the dev server from what I can tell.
