### ISSUE TITLE
downloadable False not always honored with "Download All" 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#160]
Here are two resources both are Streaming videos from DCMP one has "Download All", where the other doesn't have this this download all button.

See images:
Correct Behavior
Alt: No "Download All Files" Button
![Screen Shot 2020-06-24 at 9 37 32 AM](https://user-images.githubusercontent.com/7736749/85596565-b159e280-b5fe-11ea-8849-4d7b494b4da3.png)

Incorrect Behavior
Alt: There exists a "Download All Files" Button present
![Screen Shot 2020-06-24 at 9 37 13 AM](https://user-images.githubusercontent.com/7736749/85596678-cafb2a00-b5fe-11ea-81a0-ec23e977b674.png)

The JSON File which I imported which caused this is in 
Imageshare-utils/Data Files/Imageshare-Master.json & associated Imageshare-Master.txt

You will notice that the solution I used to duplicate the row for resource/resource file in the UFT16 txt file and it seems that because there is a link in the URI field for the resource which is the root cause here, but the file_downloadable was set to FALSE so this shouldn't have been included I guess.

This relates to #156 which was needed for resources with only one file and is provided to use in excel as one record per row, and we have thousands of these records so the easiest solution that seemed to work except for this issue was to create that duplication row script that was decided in #156.

**Comment by sinabahram** [comment]
Charles, this is behaving as designed previously, I think. You decided to duplicate rows, but we never agreed that this was a good idea, and this is one of the reasons why. You now need to redefine the logic for the "download all" behavior, right? Because, before, we used that location for the zip file with downloadable boolean set to true; whereas, now you're copying the value and expecting a different interpretation of the row. We can discuss further on Friday's call if this isn't resolved before then. I don't see a bug here. I see the software behaving per the old rules, so you need to let us know what rule updates are necessary, unless if I'm missing something.

I think what you should do is to use the script from my last commit on two TSV files. The first one, manually follow our rules for two or three entries. For the second one, do it with your duplicating script, and then compare the resulting JSON output. If the output is different, which I predict it to be, then we've identified what logic in the script needs to be changed.

If the output is the same, then the bug exists at the WP layer.

@jkva  let me know if I'm interpreting this wrong/

**Comment by clapierre** [comment]
@Sina, you are correct its just an issue with the script and that we are overloading file_downloadable / resource_downloadable which we don't have.  In the two JSON files the only difference is as I said the "URI" field for one has data which points to the DCMP streaming URI, and the other is blank.  But it is blank in one file because we manually deleted that and all other file_* items for that row in the txt CSV file.  Now we can't due that since we need to duplicate the entire row.  I think all that is needed is a small change to the tsv2json.py script that before putting the file_URI in the resources "URI" files that if file_downloadable is false then it shouldn't do that and keep it blank.  I can try to do this but yesterdays duplicaterows.py was my first ever python script.

**Comment by clapierre** [comment]
I have updated the script imageshare-util: Scripts/tsv2json.py to not include the resource URI if on that same row the file_downloadable is set to FALSE.

So I can close this out.
