### ISSUE TITLE
Move icon text off-screen

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#163]
Can we display the name of the file type on hover over those icons?  In Search Results view / Collections view.

Alt: showing "Text Document" which appears when mouse is hovering over the TXT Document Icon.

![Screen Shot 2020-06-25 at 4 35 12 AM](https://user-images.githubusercontent.com/7736749/85713024-c9347380-b69d-11ea-8e24-e6de2bd915ea.png)

**Comment by jkva** [comment]
Then the question becomes how to make that same information available to keyboard users.

**Comment by jkva** [comment]
At that point it'd be better to display it as

`[icon] Image      [icon] Text document`

I'd say.

**Comment by clapierre** [comment]
Right, since its not a tab stop you can't get at that... umm ok let me discuss with our team.

**Comment by jkva** [comment]
Implemented via 01a6edeb28443070c5c72da2b2043a2e754e161a

**Comment by clapierre** [comment]
@jkva spoke with our team and they don't like the text on the screen which defeats the purpose of the icon for the search results page.  Lets remove that text.  Ideally we would like a title for mouse over with that text but if thats an issue for keyboard access then lets not have that option either.

**Comment by sinabahram** [comment]
Charles, let’s discuss on our call. Both Job and I are deeply surprised by this request. This is basic accessibility 101 for us, so we don’t understand why we are being sked to violate WCAG here?

**Comment by clapierre** [comment]
@Sina, thats fine we don't have hover as it has the text and 99.999% of folks will know that TXT icon means a text document so I am fine with not including that.  Then both Keyboard and Mouse users have the exact same experience.  Out of curiosity how is hover ever WCAG compliant?

**Comment by sinabahram** [comment]
No, the hover is not the issue here. That’s just nicely handled by Job’s solution because it’s no longer necessary with the text. The issue is the lack of text for a non-SR user. A sighted keyboard user, cognitive impairments or not, enabling images or not, on a limited bandwidth connection or not, will not have access to what that icon means. I also do not agree that icon fluency is ubiquitous, especially amongst persons with disabilities.

**Comment by clapierre** [comment]
Then we add an Icon Descriptions legend at the bottom with all the file type icons and what they mean.

**Comment by sinabahram** [comment]
That's a ton of redundancy then and we'd have to add SR-considerations for the legend, since the images would now need to be described in that context, necessitating them to have alt text in one place but not in another place where they are used. The reason for this is because an SR user, like  a teacher, needs to be able to explain to her students what the icons mean now, so we can no longer hide them in the legend; whereas, by having the text, everyone understands them: sighted or unsighted, SR user or not, keyboard user or not, and cognitive impairments or not.

**Comment by sinabahram** [comment]
@jkva  Let's just keep the text off-screen. No legend and no hover either. Keeping the text off-screen though, just so we don't have screen reader users with "graphic" announcement. As for accessibility considerations, Benetech is completley comfortable with these icons satisfying a11y requirements as-is sans text.

**Comment by jkva** [comment]
Implemented via 1963ec7831e81a9ecaafde4d657cb4d655d3ec98
