### ISSUE TITLE
Importing unique resources

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#168]
When we import resources, what are we using to identify a resource?  Is it just the resource_unique_name? 

I am worried now if I import a different 3rd party’s resources they may have the same name for their resource and we will over write say a DCMP video with an APH’s resource.  At a minimum I would expect the Resource Name & Source be the unique identifier.

Looking at the JSON file it looks like the unique_name is also the over arching name for the JSON object, which is why I am thinking that  the unique name only is being used for the resource import.

CONFIRMED.

I created a test Imageshare-test file then ran the tsv2json.py which created the following JSON file which when imported updated the Open Stax Resource when this was a Benetech Resource  which just happens to have the same name as the Open Stax resource.

Imageshare configuration
Resource updated: Carbon Cycle
File updated: Carbon Cycle

and I confirmed that the resulting Carbon Cycle's data was changed from Open Stax to Benetech instead of having both Open Stax and Benetech's resources as separate resources.

Do we need to modify the python script to add the Source to the Resource Name in order to make them unique between different 3rd party source resources?  

[Imageshare-Test-UniqueName.xlsx](https://github.com/benetech/Imageshare/files/4880208/Imageshare-Test-UniqueName.xlsx)
[Imageshare-Test-UniqueName.txt](https://github.com/benetech/Imageshare/files/4880209/Imageshare-Test-UniqueName.txt)

(NOTE: I added .txt to the .json file since Github won't allow me to upload a .json file.)
[Imageshare-Test-UniqueName.json.txt](https://github.com/benetech/Imageshare/files/4880212/Imageshare-Test-UniqueName.json.txt)

**Comment by jkva** [comment]
> When we import resources, what are we using to identify a resource? Is it just the resource_unique_name?

That's correct.
I could change it code-wise to be a concatenation of unique_name and source, but it would semantically be better to handle this python-side, otherwise calling the field 'unique_name' becomes useless.

**Comment by clapierre** [comment]
Right I was thinking unique within this JSON record so that it was also unique for determining which files are associated with a resource.
But we are now going a step further for what it means to be unique between separate JSON files which presumably will be from different third parties.

**Comment by sinabahram** [comment]
I do agree that calling the eventual field (not just in the json) unique_name in WP land is super-problematic if it is not truly unique. So, first: is this what it is called in WP land or is it called title or name or something else when it's actually turned into a Resource object?

Now, as for where to go from here, I see two solutions:

1. We join some strings together in the json file. This is not hard to achieve, but what are the implications? One immediate implication that I worry about is the fact that now the names of resources will be longer and then subsequently present UI asks down the road and then we have this vicious cycle of where to apply bandages because that longer string is what will be used for the name of the Resource.

2. We can simply perform the uniqueness constraint of (unique_name+other-stuff) in WP at import time. If we need to change the name of the column to "name", we can, but that's purely esthetic at that point. The advantage to this solution, from what I can tell, (@jkva  tell me if I am wrong) is that then the titles of resources can remain friendly.

There are potentially other solutions as well, so let's discuss those on here too.

**Comment by clapierre** [comment]
@jkva when I updated the JSON file which is attached here, it still updated the Open-Stacks resource

in the JSON file I made the following change: (JSON object name "Carbon Cycle-Benetech" vs. "Carbon Cycle"

{
 "**Carbon Cycle-Benetech**": {
  "unique_name": "Carbon Cycle",
  "source": "Benetech",
...

vs. the original

{
 "**Carbon Cycle**": {
  "unique_name": "Carbon Cycle",
   "source": "Open Stax",
...
[Imageshare-Test2-UniqueName.json.txt](https://github.com/benetech/Imageshare/files/4880871/Imageshare-Test2-UniqueName.json.txt)


I was expecting with that change to the JSON file that would have created a new resource but it just updated the original one as well.

It looks like to me that the JSON object name which encapsulates both the resource and its files is not used at all, is that correct?

Because the unique_name seems to be the "Name" of the resource itself and is what you are using to determine if this is a new resource or not, is that true?  If so how would we modify the python script to separate both of these, it seems to me that something would also need to change at the back end?  Or am I missing something?

**Comment by jkva** [comment]
> We can simply perform the uniqueness constraint of (unique_name+other-stuff) in WP at import time. If we need to change the name of the column to "name", we can, but that's purely aesthetic at that point. The advantage to this solution, from what I can tell, (@jkva tell me if I am wrong) is that then the titles of resources can remain friendly.

Yes, this can be easily done in WP at import time. The resource field is "title" which is the proper field to use for this.
We can shift the problem to WP land, but I'd still prefer to keep it in json-generation land, otherwise the risk is changing it again, and again, as constraints change.

**Comment by jkva** [comment]
@clapierre I don't understand. You didn't update the `unique_name` value, so it update the existing resource with title "Carbon Cycle". What did you expect would happen?

The object name is not used, from what I can recall. Only the properties of the object associated with it.

**Comment by clapierre** [comment]
So should we then change the JSON format so that we have 
"name" : (which is the main resource name/title)
"unique-id" : (made up of name+source+... )

@jkva Right I thought you were using the JSON's object name for this resource but it seems you are not using that.  So that would mean we would need to add a new field in the JSON object like I suggested above with "unique-id" if we can't use the JSON"s object name which is how I originally thought you implemented this by.

**Comment by jkva** [comment]
That's why I commented on the semantic importance of having that field be called "unique_name".

It seems to me that perhaps it might be better to handle the constraint on the backend, if this is the case. `join(' ', title, subject, source)` or something to that degree.

**Comment by clapierre** [comment]
Either that or like Sina has said add a new truly unique id to the JSON file that would not be shown in the UI and is used to identify this resource uniqueness for updating purposes only.  Now does that affect the URI to a specific resource then?

IE: when I go to resources and pick one to view I get

http://imgsdev.wpengine.com/btis_resource/crazy-engineering-gecko-gripper/

would that also get updated to something like
http://imgsdev.wpengine.com/btis_resource/crazy-engineering-gecko-gripper+DCMP+Areospace/

**Comment by jkva** [comment]
In the end I set the title to whatever is in the field `unique_name`, but I can use any other arbitrary constrain to decide on uniqueness. If you want to provide, say, a UUID in the JSON, I can set that as meta data on the resource and use that for uniqueness checking.

**Comment by clapierre** [comment]
Understood @jkva, I know we can create a UUID in python easily enough and it can be based on the combination of a couple of the fields in the JSON file (name, source, and maybe subject).
@sinabahram what do you think of that?
would that UUID also now be part of the URI to that resource then I assume?

But that would then be a 36 character string that I assume would be part of the URI to that resource?

ie: http://imgsdev.wpengine.com/btis_resource/123e4567-e89b-12d3-a456-426614174000

**Comment by sinabahram** [comment]
I'm trying to recap where we are in the conversation to get us to make some decisions. Here goes.

This is critical. We have three things to resolve.

1: Unique ID for importing purposes. Yes, this can be done python-side, and needs to be a separate column. I suggest something like the hash of name+source, but this immediately surfaces an implication. What if you wish to change the source or name of a resource, you can no longer do that via importing e.g. pre-python script in the tSV. You must do it post-python script in the JSON because otherwise the new value will invalidate the hash of course. Now, given that names and sources should not change, this may be a non-issue, but we can't revisit this decision, ever, so it's critical we get it right.

Ok, think on that for a sec, while we go on to 2 and 3.

2: Name in WP. This should remain as it is now because UI and semantics and such all derive from these nice friendly names. This is an easy one I feel. Let's not change names in WP. Disagree, either of you, otherwise let's assume 2 is true while we resolve 1 and 3.

3: If 2 is true, then what do we do about Imageshare URLs? They will no longer be unique, which is of course a serious problem.

We can use IDs instead of names (I'm not in love with that and feel it's less pretty/understandable).

We can simply append a number to the end for URL purposes (@jkva  is this something that can happen easily/reliably?). I also am not in love with that.

We can append the source to the name and call it a day. I like this one a lot for our current situation. I like it because within a source there should never be duplicate names.

So, my votes are:

1. Let's hash name+source and call it unique_id, keeping unique_name called unique_name because it is unique per that file.

2. Names remain the same (simply called whatever unique_name says) in WP.

3. Let's append source to slug/identifier in WP to arrive back onto distinct unique URLs.

Thoughts, good people?

**Comment by clapierre** [comment]
That works for me and would be handled on the WP side I assume and we can leave the JSON file alone.

As for your question on issue 1 @sinabahram I agree this "could" be an issue down the road but I don't think the Source would ever change and if it does we would have to go find all those original resources and delete them before importing them with an updated source name.

Now if the resource name were changed and we didn't realize it then we would get duplicates which would have to be manually rectified.  Again something that I don't think would happen and I think is minimal risk.  So I concur with your assessment and that a new unique slug of name+source is fine.

Also not including the subject allows us to update those without worrying about creating duplicates.

**Comment by jkva** [comment]
I need to be clear. The value for `unique_name` in the JSON is used for the `title` in the resource.
The slug for that resource is generated internally by WordPress (I could override but that's not here nor there).
What matters is how I decide on which value or set of values to constrain, WordPress-side. I can do that by taking the field of `unique_name` and `source` provided in the JSON data and go from there. This will have the effect we all want.

**Comment by jkva** [comment]
By which I mean that I will change the code WordPress side which checks for existing resources to use the `unique_name` and `source` to search for previously existing resources.

**Comment by sinabahram** [comment]
@clapierre   just to confirm, you agree with my suggestions for 1, 2, and 3, yes?

**Comment by clapierre** [comment]
Yes @sinabahram and I believe that is what @jkva also is saying in his latest comments.

**Comment by sinabahram** [comment]
@jkva   can you respond to my 3 points, please? I'm trying to keep things unconfusing, and I believe I address that point in my three points post, but let me know if I do not. Trying not to go down rabbit holes of side discussions so I can keep all three points clear. But, do make sure to tell me if my three points do not address your two latest comments. Thanks so much!

**Comment by sinabahram** [comment]
@clapierre  thanks so much for confirming, and I also believe @jkva  agrees, but just waiting on explicit agreement of my 3 points. Once we have consensus, then I can implement the changes in the python script.

**Comment by jkva** [comment]
I agree with points 1 through 3. That seems like a good solution.

**Comment by sinabahram** [comment]
Ok, awesome! I'm closing this issue out so we can create 2 issues for 1 through 3. 2 is a no-op, so doesn't require an issue. @jkva, may I please ask you to create the issue for 3 involving WP, and I'll create the issue for the python script for 1.
