### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#182]
We need to make sure we are set up to receive Google Analytics for this website.
Question, what type of information will we be able to receive?
Ideally we would want to know how many visitors, and then how many downloads of the various resources downloaded.
Will we also be able to know for 3rd party resources how many folks clicked links to visit those resources such as the DCMP videos?

**Comment by johnhbenetech** [comment]
@clapierre can you put in the Jira to IT? They will need to create a new property on the Benetech Google Analytics account and then provide us as users on that property.

I'll poke around a bit at some WP add-ons, but that will almost certainly be the best approach for us because it removes the need to update any code on our end.

We will certainly get all the new/returning users, time on page, bounce rate info. I think we will have to see how we can pull off the per resource tracking most cleanly. As with any analytics, there are likely to be many different ways we can measure them, each with their own inaccuracies - so probably best to circle back when rubber hits the road.

I *think* by default, google analytics can track things on a URL-by-URL basis. So we use slug based URL for collections and resources, and then filenames for the s3 resources. It can also track external URL clicks. So if we rename collections/resources the URLs would change, and so there could be an incongruity there. There's also some stuff tracking access on the s3 side, but obviously we wouldn't see the external requests in that approach.

**Comment by clapierre** [comment]
done: https://bugs.benetech.org/browse/DSK-15222

**Comment by clapierre** [comment]
@johnhbenetech  OK IT set it up on their end.  This is what Greg wrote:


I setup the analytics under the main Benetech.org account.  Below is the tracking code you need and you can find WPEngine documentation for setting it up here: https://wpengine.com/resources/wordpress-google-analytics-tag-manager/

{noformat}

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-2390830-37"></script>
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'UA-2390830-37');
</script>
{noformat}

**Comment by johnhbenetech** [comment]
Thanks @clapierre 

I have added tracking to the Staging site using the plugin "GAinWP Google Analytics Integration for WordPress" by IntelligenceWP.

This plug-in was chosen for a few reasons. For posterity:
* Good features and control
* Doesn't require manual inclusion of tracking code
* Due to the way Timber initializes the header and footer, a lot of the more popular GA plugins don't work with our theme since they work by injecting tracking code into the header on load. This plugin injects into the body, which has a few downsides but is compatible with Timber.

Charles, we can go through the various options when we are ready to launch production. Some things to start considering: IP anonymization, user opt-out, demographic tracking, excluding us, etc.

Right now it logs downloads and external link clicks under Behavior>Events. It also logs all page views under Behavior>Site Content.
