### ISSUE TITLE
Link to Imageshare

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#201]
When SR brings up a list links.
The link just says "Imageshare" suggested from tester to change the name
"Imageshare Home"

**Comment by sinabahram** [comment]
I feel most folks know that means home page, but I'm totally ok with "Imageshare Home". The fundamental problem is not with that, but that it says "Imageshare" instead of "ImageShare", so the product name is pronounced incorrectly, but we've already pointed that out a few times, and I understand it won't change (just want to note it) as it's higher priority than "home" vs not on the link name.

**Comment by clapierre** [comment]
Right, and we have a request in at VFO or whatever they are now called to add a dictionary item for our other "share" products like they have done for "Bookshare".

**Comment by sinabahram** [comment]
Good to hear that, but I just want to point out that covers a very small percentage of folks around the world. Doesn't handle NVDA, VoiceOver on desktop or mobile, Talkback, various read outloud solutions, etc.

**Comment by clapierre** [comment]
Actually @sinabahram  we tested on those other screen readers and they all spoke Imageshare and Mathshare correctly, we tested with NVDA and VoiceOver on a Mac, only JAWS seemed to have an issue.

**Comment by sinabahram** [comment]
Sorry, but this doesn't match my experience (just re-checked to make sure). VO on iOS, which is used by a super-majority of blind folks, does not say it correctly for Mathshare nor Imageshare, and NVDA may say it correctly with espeak as the TTS, but that's not always the synthesizer that folks use with NVDA, which is why dictionary rules are a suboptimal way to go about this. However, I know it's off topic for this thread.

**Comment by jkva** [comment]
Is this ticket still relevant, and which link is being addressed? This is unclear to me right now.

**Comment by clapierre** [comment]
This is the first link on any page which is the large Imageshare logo. For the screen reader is currently says "Imageshare a Benetech Initiative" we need Home added so it should say Imageshare Home: a Benetech initiative"

**Comment by sinabahram** [comment]
This issue has gotten a bit verbose, so I hope I can clear things up.

@jkva  please make the alt text of the link read exactly as alt="Imageshare Home".

@clapierre  the current string involving the whole Benetech Initiative and all that is very much out of place there. That info is available in the footer for anyone who needs it, but it is not good link text for that home link.

That's the only change needed to close this ticket successfuly.

**Comment by jkva** [comment]
Done via 1c7b58bf75f61a0eff183606c01c1bd7a8882d54
