### ISSUE TITLE
Back to "Search results" from Resource

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#202]
If you get to a resource from a collection the link
"Go back to Search results" is incorrect since you were in a collection.

So you don't get back to the collection you were just in.
This should instead say "Back to Collection" and ideally "Back to 'Chemistry' Collection" if you came from the Chemistry collection.
And the link should bring you back to the collection not whats happening now is that it takes you to a "Search" page which had 0 parameters and lists all resources in our collection.

**Comment by sinabahram** [comment]
@clapierre  we warned about some of this when discussing the "back" functionality a long while ago. Imagine a user coming to this page fresh from a direct link, what should this link even do? It is why I absolutely dislike "back" functionality. That is what the back button on your browser is for. I think there's several edge cases to work through here, and I'm not sure we'll be able to have enough info on the server in order to craft the correct target for this link each time so I just want to set some expectations around this one.

**Comment by clapierre** [comment]
I am happy to remove our own back link given the issues raised here and use the browsers back button instead.  I would rather fix the other issues since the back button is an obvious solution.

**Comment by sinabahram** [comment]
I would be more than happy to do that. It solves so many problems! Closing this and making an issue now.
