### ISSUE TITLE
Importing updated resource and associated files did not update data

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#210]
I had a resource with 39 files and went in and uploaded a new json file which updated the author and license changed but these changes never were reflected even when published.

I am still getting the source as "Central Access" instead of "Benetech"
and the file licenses and author didn't change either.
all the PDF's should be now authored by Nichole Johnson but its still all blank when we bring up this resource.  Same for the License that was added is showing still blank or the old license we had.

It looks like its cached somewhere, but I tried in Chrome incognito.  But when I edit the resource and its file in the database it shows the correct information.

**Comment by sinabahram** [comment]
A few questions.

1: When you say you are looking at the database, you don't actually mean the real database, correct? You mean the wp-admin dashboard interface? I want to make sure we have a full understanding of the issue here.

2: Assuming the answer to 1 is yes, what I'm hearing is that the data reflects correctly, so the import worked correctly, and everything is fine in the dashboard, but these changes are not reflected on the website proper. Is that also correct?

If so, that sounds like a WP Engine caching issue perhaps?

**Comment by clapierre** [comment]
@sinabahram 
1. yes the WPEngine view of Resources and Resource Files
2. Correct database looks correct but not reflected on website.

**Comment by sinabahram** [comment]
@johnhbenetech  can you look at caching issues per the above?

**Comment by johnhbenetech** [comment]
@clapierre What resource specifically is being discussed?

**Comment by clapierre** [comment]
Frog Dissection 

@sinabahram for some reason tho the link I get is still having  the old Source "Central Access" instead of "Benetech"

ie:
http://imgsdev.wpengine.com/btis_resource/frog-dissection-2d-central-access/

But searching on "Frog dissection" and clicked on that resource thats the URL we get.

**Comment by clapierre** [comment]
Ignore, I was in Staging not dev by mistake when I did this.
