### ISSUE TITLE
Implement keyword search API endpoint

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#254]

**Comment by jkva** [comment]
@clapierre I'd like to clarify the requirements for this endpoint; is this to search by post tags?

**Comment by clapierre** [comment]
I believe this endpoint would return a list of all keywords in Imageshare, isn't this what we were thinking @sinabahram ?

So that the idea being we could scan a webpage matching all keywords in Imageshare to highlight those words found in Imageshare that are on this webpage.  

Also, for AT we could in addition to highlighting those matching keywords on the webpage would be to bring up a list of keywords in the webpage which matches Imageshare's keywords, so that then you could do a imageshare search and enter those keywords as the search parameters.

**Comment by jkva** [comment]
Endpoint implemented via 0780df6
