### ISSUE TITLE
Clone the Wordpress Clean instance in Github

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#51]
Before we start adding plugins, templates, custom css, code, etc.  I think the first task should be to clone the Wordpress Initial clean instance we have in GitHub.  So we have a baseline to start from and any new changes we will have a record of in Github and can see all changes we made right from the start of a fresh install.
Since this is a fresh install of Wordpress I assume you would be able to just clone our empty Github repository, and add in a new instance of Wordpress in that folder and push that as the first commit.

**Comment by jkva** [comment]
@clapierre I was going to raise this question today :) you want to contain an entire wordpress installation  in github, and not have either a repository containing, say `/plugin` and `/theme`, or separate `plugin` and `theme` repositories?

Either way works for me, but I want to make sure I understand the needs correctly.

**Comment by sinabahram** [comment]
Correct, this is pretty normal for sites like this. Yes, it’s technically possible to have the plugin in its own repository and the theme in another one and the WP instance in yet a third one (that’s the one that gets used for delivery), but I don’t think the Git operations here are developed enough to really sustain that, so let’s keep things simple for now. The plugin and theme can always be split out very easily/trivially because they are a plugin and a theme if separate repos are needed in the future.

**Comment by clapierre** [comment]
I agree lets keep it all together for now.

**Comment by jkva** [comment]
Resolved through 00e61ab.
