### ISSUE TITLE
JSON Manifest

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#71]
JSON will be the primary way to add bulk resources to Imageshare.
We currently have some CSV files for the current Imageshare resources that we need to clean up and then convert into JSON files. I will create another ticket that will include the original DCMP cvs file and work on the schema of what column names we will require and which column  names will be optional.

This ticket we need to finalize the JSON manifest schema to use.

@jkva @jscholes to add additional information to this ticket.

**Comment by jkva** [comment]
After discussion with @sinabahram it's likely we'll still be parsing external manifest files that in a non-json structured format such as csv. These will map to the Imageshare internal model format.

This should be validated against a schema which should should be JSON. This will also allow for easy future modification.

A good standards following validator is https://github.com/swaggest/php-json-schema.

**Comment by sinabahram** [comment]
@jkva, I want to be a bit more clear about that, because I think that’s mostly correct, but not fully correct.

Currently, Benetech has lots of csv files in various schemas, etc.; however, we will still accept only JSON input. It’s just that this JSON could easily come from output of a conversion of a csv file on the Benetech side; however, let’s have the csv to JSON conversion happen before the file is posted, unless if that’s super-trivial to do server-side. Trying to have less things that can break in production, here, so if the server can just always speak JSON, that's one less thing to go wrong

The only reason i say it may start out as a CSV on the Benetech side is because Excel and Sheets makes this kind of thing easier to deal with, so they can convert ot JSON as their last step before import.

@clapierre  is working on a sample for us in this csv format, which we can trivially convert to JSON with various existing command line tools. He's going to put 10 rows of data from different sources and types in so we have a nice variety to test with. He and I both discussed the importance of having a finalized list of columns, or fields, for each Resource, so we should try to arrive at a first final list in the next 24 hours or so.

I say first because I think we will end up adding a bit to these columns, but hoping to crystalize that structure by end of week, or at least by the time the mockups can be played with a bit to give people a chance to invision anything that's been critically left out.

We also chatted about the fact that these CSVs need to be normalized on Benetech's end.

I think that's everything.

**Comment by clapierre** [comment]
Yes I am working on this today!

**Comment by sinabahram** [comment]
This is addressed by future issues.
