### ISSUE TITLE
Various accessibility fixes

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#86]
* Page title on search result should be "Search results for photo - Imageshare"
* Resource page title should be "[Resource title] resource - Imageshare"
* Check out if advanced search expand/collapse is working correctly. Looks like a bug.
* Remove `role=list` of `ul` in mock theme
* Remove `role=img` on `a` of search result in mock theme
* Resource image should be click target for sighted users only
* Remove `h2` above table of search results
* Remove `describedby` from search result
* Add caption to search results label, `sr-only`. Daughter should be `h2`.
* Fix resource thumbnail alt text
* Fix horizontal scroll on search results

**Comment by jscholes** [comment]
> Check out if advanced search expand/collapse is working correctly. Looks like a bug.

Could you expand on why it looks like a bug?

> Remove `role=list` of ul in mock theme

Given that this doesn't have any negative impact, I think it should remain.  It's a VO-specific work-around to avoid list semantics being stripped when you provide the list with an accessible name.  That represents a VO bug and if we don't want to support those, it can go.  But keeping it is also fine.

> Remove h2 above table of search results

Why?  Presumably it separates the table of results from what comes before it.

> Remove describedby from search result

What does the value point to?

**Comment by clapierre** [comment]
We definitely need to support Mac's with Safari and users using Voice Over, I didn't know about this issue but I agree having the same role=list for a list is fine and if it fixes a VO bug then lets leave it as I would rather not having to deal with forcing Apple to fix that.

**Comment by sinabahram** [comment]
@jscholes  these came from me but weren't perhaps written for anyone other than Job taking notes for himself, but see below as you've convinced me on role="list.

you asked:
Check out if advanced search expand/collapse is working correctly. Looks like a bug.

SB: Yup, sure can. Go do a search, and on the resulting search results page, aria-expanded is equal to true on the button. If you hit hit, nothing appears to happen, but I believe it visually then expands, and then if you hit it again, it is back in sync.

The solution, I hope, is to trigger the CSS behavior off of the aria-expanded, if possible. This way, @jkva  when something like this is broken, it breaks for everyone and is easy to detect/fix.

you asked:
Remove `role=list` of ul in mock theme

Given that this doesn't have any negative impact, I think it should remain. It's a VO-specific work-around to avoid list semantics being stripped when you provide the list with an accessible name. That represents a VO bug and if we don't want to support those, it can go. But keeping it is also fine.

SB: Yes, this can stay, @jkva because @jscholes  is totally right. For the record, though, it makes me very sad. Thanks Apple. Thanks a lot.

you asked:
Remove h2 above table of search resultsSB:

Why? Presumably it separates the table of results from what comes before it.

SB: because it is in the wrong place. It belongs above the table, and Job was speaking visually not semantically. It's too much above the table e.g. it's above the pagination update and such. I told him to do the caption with daughter of h2 for table name, unless if you disagree? This eliminates some aria, which is always preferable, and it gets the heading to be in the right place.

This should have read move h2 above table to be the daughter of the caption after adding caption to search results table, but we were on a call and I was peppering @jkva  with issues.

you asked:
Remove describedby from search result

What does the value point to?

SB: the main heading. This is useless and I have no clue why it's there. I also don't even think it's spec. We don't need either aria-labelledby or aria-describedby on this table if we ad the caption per the above, right? So I want both gone unless if you disagree.

@jkva  as long as @jscholes  confirms the above, please proceed with these updates in mind e.g. don't remove the role="list" thing.

**Comment by jkva** [comment]
> @jkva as long as @jscholes confirms the above, please proceed with these updates in mind e.g. don't remove the role="list" thing.

That's fine. I'll be reluctant. As far as I know the list role semantics being stripped by voiceover is a _feature_ for users not having to listen to list semantics being rattled off when stylistically it's not a list. I agree with the questionable usefulness of that, so I'm fine with leaving it on.

**Comment by sinabahram** [comment]
Please proceed with it, though. Apple is wrong here, as is unfortunately a bit too common on web accessibility issues. They don’t get to decide a decorative list on a whim, and they are frankly making the web less, not more, accessible through this silly choice. I can discuss this with them to at least flag it, but it’s obviously intentional, if not misguided, as you point out.

**Comment by jkva** [comment]
Implemented via 5d501400fe1fe15383ac2431a01e57fbab04da0a
