### ISSUE TITLE
Display of subjects in select

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#95]
@jkva  please go specific to general e.g. instead of doing "Physics - Mechanical Motion" do "Mechanical Motion - Physics".

**Comment by jkva** [comment]
Implemented via 131f09f30ee6c13daa32ab626777fb47bde220ad

**Comment by clapierre** [comment]
After extensive user testing turns out everyone wants all the "Engineering" or "Science" topics to be together.  so unfortunately we need to revert this back so when you do an advance search you get

"Engineering - Aerospace"
"Engineering - Agricultural"
"Engineering - Chemical"
etc. instead of what we have now with the sub-topic for the given main subject area being first.

They also expected to have to Hit "E" multiple times to hear all the different Engineering subject areas.

So please revert this change, as this was one of the highest issues with advance search.
Ideally they would ultimately like to select the main Subject and then based on what they chose show only a narrowed list of sub topics under this but that will be for a future release.

**Comment by jkva** [comment]
Modified it in the search form.
Left it the way it was on the resource details
![image](https://user-images.githubusercontent.com/217264/88700753-65bcbc00-d109-11ea-8da7-032ecf4ac01f.png)
is that okay?

**Comment by clapierre** [comment]
That is fine to have it this way on the resource Subject view.  Thanks for asking.

**Comment by jkva** [comment]
Implemented via 2d7b434e95d1f40a6b4f7d611aea2981a792d4e9

**Comment by clapierre** [comment]
@jkva is it expected you can't press "E" multiple times to get through all the Engineering topics?

**Comment by sinabahram** [comment]
@clapierre  that is OS/browser-specific behavior, but it does work over here in Windows. I went through with repeated presses of 'E'. If Mac doesn't support that, then yes, it is working as expected.

**Comment by clapierre** [comment]
Oh because previously I could press A multiple times to get through all the sub-topics. so it just seems odd now that it doesn't work like that when we reversed the Main subject and sub-topic areas.

**Comment by clapierre** [comment]
Weird, its now working as expected. here too.  So odd. Thanks!

**Comment by sinabahram** [comment]
Sorry, I don't understand at all. This works exactly like every other select on my computer. What's the issue here?

**Comment by clapierre** [comment]
@sinabahram its working now no worries.
